name: Frontend CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  detect:

    runs-on: self-hosted

    outputs:
      client: ${{ steps.filter.outputs.client }}
      admin: ${{ steps.filter.outputs.admin }}

    steps:

      - uses: actions/checkout@v5

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'Client/**'

            admin:
              - 'Admin/**'

################################################################################
# CLIENT
################################################################################

  client:

    needs: detect

    if: needs.detect.outputs.client == 'true'

    runs-on: self-hosted

    defaults:
      run:
        working-directory: Client

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint || true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/client:latest \
            -t ghcr.io/${{ github.repository_owner }}/client:${{ github.sha }} \
            ./Client

      - name: Push
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/client:latest
          docker push ghcr.io/${{ github.repository_owner }}/client:${{ github.sha }}
################################################################################
# ADMIN
################################################################################

  admin:

    needs: detect

    if: needs.detect.outputs.admin == 'true'

    runs-on: self-hosted

    defaults:
      run:
        working-directory: Admin

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint || true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build \
           -t ghcr.io/${{ github.repository_owner }}/client:latest \
           -t ghcr.io/${{ github.repository_owner }}/client:${{ github.sha }} \
            ./Client

      - name: Push
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/client:latest
          docker push ghcr.io/${{ github.repository_owner }}/client:${{ github.sha }}
